### ISSUE TITLE
composer require oakhope/aliyun-sms  报错

### ISSUE THREAD

**Issue by geita** [oakhope/aliyun-sms#1]
您好作者，我通过composer require oakhope/aliyun-sms     安装sdk，会报一下错误，请求您的帮助。

![aliyun2](https://cloud.githubusercontent.com/assets/14833694/26781142/a0a7f894-4a1f-11e7-86f5-69b6ccac19e8.png)

**Comment by oakhope** [comment]
谢谢反馈！我晚上回去了看看，然后回复你，非常感谢

**Comment by oakhope** [comment]
@geita 谢谢反馈，我小改了下，有空的话可以试下 :)

**Comment by geita** [comment]
作者您好，我今天一上班就测试了，测试结果：ok。非常感谢您，这个问题我我昨天研究了好久，发现的原因是因为项目中我用到的有阿里云的oss，而oss和短信 都会用到这个类文件  guzzlehttp文件。我昨天的办法是把mns-autoloader.php文件中最后三行引用代码删除了，问题也是解决了。

我看见是是把文件名修改了，这样也是解决了问题，你的解决办法比较好。再次感谢您。

**Comment by oakhope** [comment]
@geita :) 并非改名，把sdk的依赖用composer引入避免了冲突
