### ISSUE TITLE
您好，可否降低PHP版本的依赖

### ISSUE THREAD

**Issue by clh021** [oakhope/aliyun-sms#2]
您好，我在网络上找了很多类似基于 阿里新版的短信服务，要传递7个参数的短信接口。
很多包都没有给出7个参数的配置。
您这边，我可以自己写配置。

但是，却依赖了PHP7.0。我的PHP5.6.30是目前服务器主流配置，却无法安装。
恳请您稍微测试一下 5.6 ，如果没有问题，就可以造福更多人了。

**Comment by oakhope** [comment]
5.6肯定没问题，代码没几行。谢谢你，我稍后改下通知你 :)

**Comment by oakhope** [comment]
简单看了下，代码没改，依赖降低了，没测。劳烦您有时间试用一下。您那运行结果是否正常劳烦告知我下 :) 嘿嘿，谢谢。
另外，你是深度公司的？我从小就是深度系统的忠实用户啊，给人装机无数，用的也都是深度win。

**Comment by clh021** [comment]
谢谢您这么快的回馈，我测试了，成功了。
但是有两个小细节，可以做的更好。

第一个，无论发送是否成功，返回的最终结果始终是true，建议返回完整的阿里端口结果。
第二个，发送的验证码必须是字符串才会成功，您那边也许可以转一下。
```
$randNum=rand(100000, 999999);
$res = $aliyunSms->sendOne($templateCode, $phone, ['code' => strval($randNum), 'product' => $product]);
var_dump($res);
```
如果没有strval会失败，加上就成功，但是无论是否成功，最终的 res 都是true(即使填写了一个包含字母的手机号码)。

最后还是非常感谢您，制作了如此方便的插件，造福广大水深火热的程序猿们。致敬！

**Comment by oakhope** [comment]
谢谢你的保贵意见，我马上修改

**Comment by clh021** [comment]
如此敬业！想说，不用太急，已经可以用了，已经超越大多数短信包了，注意身体，注意休息。

**Comment by oakhope** [comment]
参数值自动转字串的功能改好发布了，0.0.3版本，那个返回值总为true的还没有处理
