### ISSUE TITLE
endpoint问题

### ISSUE THREAD

**Issue by InVinCiblezz** [oakhope/aliyun-sms#4]
endpoint格式是什么？cn-hangzhou似乎不行
还有一个疑问topicName是什么？文档没看到

**Comment by oakhope** [comment]
@InVinCiblezz 
endPoint = https://12345678.mns.cn-hangzhou.aliyuncs.com/
topicName = sms.topic-cn-hangzhou
在你的阿里控制台应该可以找到类似如上的信息。消息服务，短信概览，大约在屏幕中央，可见到主题和endpoint
